export enum AUTH_ACTION_TYPES {
    REGISTER_START="auth/REGISTER_START",
    REGISTER_FAILURE="auth/REGISTER_FAILURE",
    REGISTER_SUCCESS="auth/REGISTER_SUCCESS",

    EMAIL_SIGNIN_START="auth/EMAIL_SIGNIN_START",
    GOOGLE_SIGNIN_START="auth/GOOGLE_SIGNIN_START",
    GOOGLE_SIGNIN_COMPLETE="auth/GOOGLE_SIGNIN_COMPLETE",
    SIGNIN_FAILURE="auth/SIGNIN_FAILURE",
    SIGNIN_SUCCESS="auth/SIGNIN_SUCCESS",
    
    UPDATE_USER_START="auth/UPDATE_USER_START",
    UPDATE_USER_FAILURE="auth/UPDATE_USER_FAILURE",
    UPDATE_USER_SUCCESS="auth/UPDATE_USER_SUCCESS",

    LOGOUT_START="auth/LOGOUT_START",
    LOGOUT_FAILURE="auth/LOGOUT_FAILURE",
    LOGOUT_SUCCESS="auth/LOGOUT_SUCCESS",

    GET_CURRENT_USER="auth/GET_CURRENT_USER",
    SET_CURRENT_USER="auth/SET_CURRENT_USER",
    CLEAR_AUTH_ERROR="auth/CLEAR_AUTH_ERROR",

    CLEAR_NAVIGATE_TO_SIGN_IN="auth/CLEAR_NAVIGATE_TO_SIGN_IN"
}